[package]
name = "crates"
version = "0.1.0"
edition = "2021"

# Required to publish on crate.io
license = "	GPL-3.0"
description = "A test package to play with crates.io."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
